
// exercicio 01 //

let num1 = 25
let num2 = 10
let soma = num1 + num2;
console.log (" a soma é", soma) ;

// exercicio 02 //

let nume1 = 15
let nume2 = 5
let diferenca = nume1 - nume2;
console.log(" a diferença é", diferenca);

// exercicio 03 //

let number1 = 5
let number2 = 5
let produto = number1 * number2;
console.log("o produto é", produto);

// exercicio 04 //

let Num4 = 4
let Num5 = 2
 let divisao = Num4 / Num5;
 console.log(" o resultado da divisão é", divisao);

 // exercicio 05 //

 let numero= 5;
function verificarParouImpar(num) {

    if (num % 2===0) {
    return "par"; }
 
    else {
return "impar";  }
}
console.log("O número", numero, "é",
verificarParouImpar ( numero));